site_name: Offline A to Z
nav:
  - "index.md"
  - Preparation:
      - Supplies purchasing: "Preparation/supplies_purchasing.md"
      - Vial cleaning: "Preparation/vial_cleaning.md"
      - Filter extraction: "Preparation/Filter_extraction.md"

  - Instrumental analysis:
      - Instrument tutorial: "Instrument_setup/Instrument_knowledge_outline.md"
      - System set-up: "Instrument_setup/System_set-up.md"
      - Pre-test: "Instrument_setup/Pre-test.md"          
      - Daily check: "Instrument_setup/Daily_check.md"   
  

  - Data processing:
      - AMS: ""
      - EESI-TOF: ""      
      - Orbitrap: ""            

  - Knowledge base:
      - Reading list: "Knowledge_base/reading_list.md"
      
  - "about.md"

theme:
  name: material
  nav_style: light
  #custom_dir: docs/resources/
  highlightjs: true
  hljs_languages:
    - yaml
  features:
    - content.tabs.link
  palette:
    primary: indigo
  favicon: images/atom.svg
  logo: images/book-open-page-variant-outline.png

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - callouts
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

extra_css:
  - resources/css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js